### ISSUE TITLE
default options for input do not set statsd prots

### ISSUE THREAD

**Issue by okrabbe** [splunk/splunk-app-statsdician#4]
If I do not set any port and instead leave it to the default, the ports do not get automatically set to the defaults.

You can compare my two inputs from my btool output.  statsd I specified the port, stats2 I did not.

[statsdician://stats2]
_rcvbuf = 1572864
dedicatedIoThreads = 2
disabled = 0
enableSSL = 1
hec_event_per_metric = 1
hec_ssl = 1
hec_token = 6BB99785-31B8-4300-9CFF-767ACF313419
host = sluedtke-mbpr15
index = test
maxSockets = 0
maxThreads = 0
port = 8088
useDeploymentServer = 0
[statsdician://statsd]
_rcvbuf = 1572864
dedicatedIoThreads = 2
disabled = 1
enableSSL = 1
hec_event_per_metric = 1
hec_port = 8088
hec_ssl = 1
hec_token = 6BB99785-31B8-4300-9CFF-767ACF313419
host = sluedtke-mbpr15
index = test
maxSockets = 0
maxThreads = 0
mgmt_port = 8126
port = 8088
statsd_port = 8125
useDeploymentServer = 0

**Comment by glennblock** [comment]
Now i see what you mean. You won't see them in the stanzas.

The statsd ports are written to the statsd config file during validate if
the ports are not provided. Statsd itself relies on the statsd config. If
you modify the ports those are also written to that config. Validate does
not allow me to change what is written to the stanzas, only validate it. To
make them persist i would have to call back to the REST API and find the
stanzas and modify them. It didn't seem necessary.

One bug I do see though is the hec port is not being defaulted at runtime,
which I will fix.

You can see the logic which persists to the statsd conf here.

https://github.com/splunk/splunk-app-statsdician/blob/master/bin/app/statsdInput.js

**Comment by okrabbe** [comment]
Oh ok I see.

Yeah, must have just been the heck_port not being defined that caused it to not work.

Omid

**Comment by glennblock** [comment]
I will fix!

**Comment by glennblock** [comment]
Thinking more, i should move the logic that writes to the config to when
streaming happens. This way if someone manually modifies the stanzas via
conf flies, the statsd config is updated?

My main reason for jumping through the hoops was to allow a user to
configure ports from the UI and not to have to open a text editor.

Alternatively I could remove those ports altogether and say modify the
config file when you install. That would make it not remotely usable in
cloud though and I think even for enterprise not as user friendly.

Thoughts
Glenn
